version: "3.7"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./back/docker/volumes/mongodb_data_container:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
